require("plug.mason")
require("plug.mason-lspconfig")
require("plug.lspconfig")
require("plug.oil")
require("plug.leap")
require("plug.blink")
require("plug.bufferline")
require("plug.treesitter")
require("plug.telescope")
require("plug.lualine")
require("plug.fugitive")
-- require("plug.indent-blankline")
require("plug.rainbow-delimiters")
require("plug.which-key")
require("plug.otter")
require("plug.mini")
-- require("plug.smear-cursor")
